version: "3.9"
services:
  master:
    build: ./target/docker/stage
#    volumes:
#      - .:/code
    command: "8080 8082 8084"
    ports:
      - "8080:8080"
  secondary:
    build: ./secondary/target/docker/stage
    command: "8081 8082"
    ports:
      - "8081:8081"
      - "8082:8082"
  secondary2:
    build: ./secondary/target/docker/stage
    command: "8083 8084"
    ports:
      - "8083:8083"
      - "8084:8084"
